import type { Achievement, Game, Platform } from './types';

export type CatalogGame = {
  id: string;
  platform: Platform;
  title: string;
  artwork?: string;
  sourceUrl?: string;
  achievements: Achievement[];
};

function ach(id: string, platform: Platform, title: string, description: string, extra: Partial<Achievement> = {}): Achievement {
  return {
    id,
    platform,
    title,
    description,
    unlocked: false,
    ...extra,
  };
}

export const CATALOG_GAMES: CatalogGame[] = [
  {
    id: 'ps-astros-playroom',
    platform: 'psn',
    title: "Astro's Playroom",
    artwork: 'https://image.api.playstation.com/vulcan/ap/rnd/202008/1721/4YJ4dQY3M6Y4_512.png',
    sourceUrl: 'https://www.eurogamer.net/astros-playroom-trophy-list-how-unlock-hidden-dlc-trophies-7058',
    achievements: [
      ach('ps-astro-01', 'psn', "You've Only Done Everything", 'Found all trophies in Astro\'s Playroom.', { psn: { tier: 'platinum' } }),
      ach('ps-astro-02', 'psn', 'Do it!', 'Cleared Memory Meadow.', { psn: { tier: 'silver' } }),
      ach('ps-astro-03', 'psn', 'Emotion Engine!', 'Cleared SSD Speedway.', { psn: { tier: 'silver' } }),
      ach('ps-astro-04', 'psn', 'HD graphics!', 'Cleared Cooling Springs.', { psn: { tier: 'silver' } }),
      ach('ps-astro-05', 'psn', 'Greatness Awaits!', 'Cleared GPU Jungle.', { psn: { tier: 'silver' } }),
      ach('ps-astro-06', 'psn', 'In Mint Condition', 'Got your first artefact!', { psn: { tier: 'bronze' } }),
      ach('ps-astro-07', 'psn', 'Such a Big Fan!', 'Got all artefacts in Cooling Springs.', { psn: { tier: 'silver' } }),
      ach('ps-astro-08', 'psn', 'Charted!', 'Got all artefacts in GPU Jungle.', { psn: { tier: 'silver' } }),
      ach('ps-astro-09', 'psn', 'Welcome to the Third Place', 'Got all artefacts in SSD Speedway.', { psn: { tier: 'silver' } }),
      ach('ps-astro-10', 'psn', '... And Conquered Worlds', 'Got all artefacts in Memory Meadow.', { psn: { tier: 'silver' } }),
      ach('ps-astro-11', 'psn', 'Dude Raider!', 'Collected all artefacts in the four main stages and the PS Labo.', { psn: { tier: 'gold' } }),
      ach('ps-astro-12', 'psn', 'One Down, Lots More to Go!', 'Got your first puzzle piece.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-13', 'psn', 'Cool Hoarder', 'Got all puzzle pieces in Cooling Springs.', { psn: { tier: 'silver' } }),
      ach('ps-astro-14', 'psn', 'The Found Legacy', 'Got all puzzle pieces in GPU Jungle.', { psn: { tier: 'silver' } }),
      ach('ps-astro-15', 'psn', 'Omega Booster!', 'Got all puzzle pieces in SSD Speedway.', { psn: { tier: 'silver' } }),
      ach('ps-astro-16', 'psn', 'Ico-nic', 'Got all the puzzle pieces in Memory Meadow.', { psn: { tier: 'silver' } }),
      ach('ps-astro-17', 'psn', 'A Grand Tour!', 'Got all puzzle pieces in the game.', { psn: { tier: 'gold' } }),
      ach('ps-astro-18', 'psn', 'Gatcha Beginner', 'Got your first Gatcha prize.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-19', 'psn', 'For the Players!', 'Got a secret gatcha.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-20', 'psn', 'Gatcha Maniac', 'Got half the gatcha prizes.', { psn: { tier: 'silver' } }),
      ach('ps-astro-21', 'psn', 'Saru Gatcha!', 'Got all gatcha prizes.', { psn: { tier: 'gold' } }),
      ach('ps-astro-22', 'psn', 'Project Neo', 'Sent 10 bots flying with a single spin attack.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-23', 'psn', 'The Last Guy', 'Walked around with at least 20 bots following you in CPU Plaza.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-24', 'psn', 'Keepy Uppies', 'Juggled a ball five times with the Frog suit.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-25', 'psn', 'Wipeout!', 'Got a strike in Memory Meadow.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-26', 'psn', 'Ready for the Proving', "Deflected a Spitter's attack with an arrow.", { psn: { tier: 'bronze' } }),
      ach('ps-astro-27', 'psn', 'No No No Noooooo!', 'Fell 30 meters and caught yourself in the monkey suit in GPU Jungle.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-28', 'psn', "It's All in the Mind", 'Beat 3 enemies quickly by punching them.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-29', 'psn', 'This Way Up', 'Punched the PS Logo on the PS2 in PlayStation Labo.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-30', 'psn', 'You Got a Trophy!', 'Picked up a trophy in PlayStation Labo.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-31', 'psn', 'I Recognise You...', 'Punched and looked into the lens of PS VR in PlayStation Labo.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-32', 'psn', 'The Very Far Point...', 'Stood on the tip of the Aim Controller in PlayStation Labo.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-33', 'psn', "Honey, I'm Home!", 'Walked under the PlayStation Home icon in PlayStation Labo.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-34', 'psn', 'Disc Swap!', 'Opened the lid of the PlayStation console in PlayStation Labo.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-35', 'psn', 'Hell Diver', 'Dived into the water from the diving board.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-36', 'psn', 'Jumping Splash!', 'Jumped in the fountain near the final goal in Cooling Springs.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-37', 'psn', 'Twisting Metal', 'Jumped three times during a spin attack on ice.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-38', 'psn', 'Jason!', 'Sheltered from the heavy rain in Memory Meadow.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-39', 'psn', 'Pain!', 'Got hit by flying rubbish in Memory Meadow.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-40', 'psn', 'Little Rolling Star...', 'Made a huge snowball.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-41', 'psn', 'Adequate, Boy...', 'Hit all rabbits with arrows at the mountain peak of GPU Jungle.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-42', 'psn', 'Wild Arms', 'Performed a spin while shooting the machine gun.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-43', 'psn', 'Super Computer', 'Revealed former logo in PlayStation Labo.', { psn: { tier: 'bronze' } }),
      ach('ps-astro-44', 'psn', 'Play Has No Limits!', 'Cleared the game and got the New Generation artefacts.', { psn: { tier: 'gold' } }),
      ach('ps-astro-45', 'psn', 'Run Astro Run!', 'Got a total Speed Run time of seven minutes or under.', { psn: { tier: 'gold' } }),
      ach('ps-astro-46', 'psn', 'Gravity Daze!', 'Made the CPU Chip punch the glass sphere, sending at least 10 Bots flying.', { psn: { tier: 'bronze' } }),
    ],
  },
  {
    id: 'xbox-halo-infinite',
    platform: 'xbox',
    title: 'Halo Infinite',
    artwork: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1240440/header.jpg',
    sourceUrl: 'https://www.halopedia.org/Achievements_(Halo_Infinite)',
    achievements: [
      ach('xbox-halo-01', 'xbox', 'First Contact', 'Lost, and found.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-02', 'xbox', 'Together. Again?', 'Explored the underbelly of Zeta Halo and retrieved a weapon to turn the tide of this conflict.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-03', 'xbox', 'Ascension', 'Defeated the Banished warlord Tremonius.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-04', 'xbox', 'Zeta', 'Fought your way through Outpost Tremonius and stepped out onto the surface of Zeta Halo.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-05', 'xbox', 'Fallen', 'Followed the UNSC signal to a Banished stronghold called the Tower. Found the source. Got out alive.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-06', 'xbox', 'Unearthed', 'Shut down the Banished mining laser and gained access to the Conservatory.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-07', 'xbox', 'Hunter. Killer.', 'Defeated the Hunter pair stationed at the base of the Spire.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-08', 'xbox', 'Pelican Down', "Shut down the first Spire and stopped Zeta's Reformation.", { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-09', 'xbox', 'Brothers Grim', 'Took down the Spartan Killers Hyperius and Tovarus.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-10', 'xbox', 'Light the Way', 'Reached the Beacons, assembled the Sequence, and gained access to the Command Spire.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-11', 'xbox', 'What Will it Take?', "Entered the Nexus and learned the secrets of the Spires. Trust is a fragile thing, isn't it?", { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-12', 'xbox', 'Hear These Words!', 'Infiltrated the Command Spire and put an end to the Reformation.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-13', 'xbox', 'Together. Again.', 'A friend was in danger and time is running out. It is time to face your past and save your future.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-14', 'xbox', 'Reckoning', 'Stormed the House of Reckoning.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-15', 'xbox', 'Legends', 'At the end he was just a soldier. Hoping he had done the right thing.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-16', 'xbox', 'Too Many Goodbyes', 'Defeated the Harbinger. Confronted the truth.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-17', 'xbox', 'Set a Fire in Your Heart', 'Completed the main campaign.', { xbox: { gamerscore: 30 } }),
      ach('xbox-halo-18', 'xbox', 'Bare Your Fangs', 'Completed the main campaign on Normal difficulty.', { xbox: { gamerscore: 30 } }),
      ach('xbox-halo-19', 'xbox', 'Fight Hard, Die Well', 'Completed all main campaign missions on Heroic difficulty.', { xbox: { gamerscore: 30 } }),
      ach('xbox-halo-20', 'xbox', 'A True Test of Legends', 'Completed all main campaign missions on Legendary difficulty.', { xbox: { gamerscore: 30 } }),
      ach('xbox-halo-21', 'xbox', 'Headmaster', 'Completed all main missions on Legendary with all Skulls active.', { xbox: { gamerscore: 100 } }),
      ach('xbox-halo-22', 'xbox', 'Forza Veloce', 'Completed all 14 main missions in under eight hours.', { xbox: { gamerscore: 40 } }),
      ach('xbox-halo-23', 'xbox', 'Evasive Maneuvers', 'Unlocked the Thruster ability.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-24', 'xbox', 'Grab Some Cover', 'Unlocked the Drop Wall ability.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-25', 'xbox', 'Visionary', 'Unlocked the Threat Sensor ability.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-26', 'xbox', 'Reclaimer', 'Captured your first Forward Operating Base.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-27', 'xbox', 'Resurgency', 'Captured all available Forward Operating Bases.', { xbox: { gamerscore: 20 } }),
      ach('xbox-halo-28', 'xbox', 'Who is Max Valor?', 'Completed all Valor-awarding activities.', { xbox: { gamerscore: 40 } }),
      ach('xbox-halo-29', 'xbox', 'Headhunter', 'Eliminated a Banished High-Value Target.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-30', 'xbox', "Bloodstars' Bane", 'Eliminated all 15 Banished High-Value Targets.', { xbox: { gamerscore: 20 } }),
      ach('xbox-halo-31', 'xbox', 'Hidden Experience', 'Located and secured a Spartan Core.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-32', 'xbox', 'Mjolnir Master', 'Acquired all Spartan Cores.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-33', 'xbox', 'Headstrong', 'Discovered your first hidden Skull.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-34', 'xbox', 'Catacomb', 'Discovered all hidden Skulls.', { xbox: { gamerscore: 20 } }),
      ach('xbox-halo-35', 'xbox', 'Please Shut Up', 'Took out a Banished Propaganda Tower.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-36', 'xbox', 'Off the Air', 'Destroyed 40 Banished Propaganda Towers.', { xbox: { gamerscore: 20 } }),
      ach('xbox-halo-37', 'xbox', 'Gun Runner', 'Took down all three Banished AA guns in under 20 minutes.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-38', 'xbox', 'Whip-Riding the Ghost', 'Used the Grappleshot to board an enemy Ghost.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-39', 'xbox', 'Wait, I Can Throw Those?', 'Threw 50 fusion coils.', { xbox: { gamerscore: 10 } }),
      ach('xbox-halo-40', 'xbox', 'Wanna Have a Catch?', 'Stuck 50 enemies with grenades.', { xbox: { gamerscore: 10 } }),
    ],
  },
  {
    id: 'steam-hades',
    platform: 'steam',
    title: 'Hades',
    artwork: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/header.jpg',
    sourceUrl: 'https://steamcommunity.com/stats/1145360/achievements',
    achievements: [
      ach('steam-hades-01', 'steam', 'Escaped Tartarus', 'Clear Tartarus'),
      ach('steam-hades-02', 'steam', 'Escaped Asphodel', 'Clear Asphodel'),
      ach('steam-hades-03', 'steam', 'Arms Collector', 'Unlock each of the Infernal Arms'),
      ach('steam-hades-04', 'steam', 'Friends in High Places', "Use Greater Call to invoke an Olympian's aid"),
      ach('steam-hades-05', 'steam', 'Escaped Elysium', 'Clear Elysium'),
      ach('steam-hades-06', 'steam', 'Chthonic Colleagues', "Fulfill the 'Chthonic Colleagues' Prophecy"),
      ach('steam-hades-07', 'steam', 'Is There No Escape?', 'Clear an escape attempt'),
      ach('steam-hades-08', 'steam', 'Death Dealer', 'Beat Thanatos by 15 kills or more'),
      ach('steam-hades-09', 'steam', 'Skelly Slayer', 'Slay Skelly 15 times'),
      ach('steam-hades-10', 'steam', 'Well Stocked', "Buy 9 'Well of Charon' items in one escape attempt"),
      ach('steam-hades-11', 'steam', 'Three-Headed Boy', 'Pet Cerberus 10 times'),
      ach('steam-hades-12', 'steam', 'Day-or-Night Trader', 'Trade 20 times with the Wretched Broker'),
      ach('steam-hades-13', 'steam', 'Back to Work', 'Earn access to and enter the Administrative Chamber'),
      ach('steam-hades-14', 'steam', 'Blessed by the Gods', 'Choose 100 different Olympian Boon effects'),
      ach('steam-hades-15', 'steam', 'Blood Bound', 'Max any Weapon Aspect'),
      ach('steam-hades-16', 'steam', 'Urge to Sing', 'Compel Orpheus to sing again'),
      ach('steam-hades-17', 'steam', 'Grown Close', 'Forge a bond with any character'),
      ach('steam-hades-18', 'steam', 'River Denizens', 'Catch a fish from each region'),
      ach('steam-hades-19', 'steam', 'Home Makeover', 'Pay for 50 jobs from the House Contractor'),
      ach('steam-hades-20', 'steam', 'The Family Secret', 'Complete the main quest in the story'),
      ach('steam-hades-21', 'steam', 'Had to Happen', 'Fulfill any 15 Prophecies'),
      ach('steam-hades-22', 'steam', "To Charon's Credit", 'Earn a Loyalty Card'),
      ach('steam-hades-23', 'steam', 'Tools of the Architect', 'Choose 50 different Daedalus Hammer enchantments'),
      ach('steam-hades-24', 'steam', 'Rare Collectible', 'Equip a Chthonic Companion'),
      ach('steam-hades-25', 'steam', 'Master of Arms', "Fulfill the 'Master of Arms' Prophecy"),
      ach('steam-hades-26', 'steam', 'Weapon of Fate', 'Clear an escape attempt with a hidden Weapon Aspect'),
      ach('steam-hades-27', 'steam', 'Something From Everyone', 'Unlock each standard Keepsake'),
      ach('steam-hades-28', 'steam', 'Hold the Onions', 'Clear an Infernal Gate without taking damage'),
      ach('steam-hades-29', 'steam', 'Well Versed', "Fully Unlock the Olympians' Codex entries"),
      ach('steam-hades-30', 'steam', "War-God's Bloodlust", "Fulfill the 'War-God's Bloodlust' Prophecy"),
      ach('steam-hades-31', 'steam', 'Champion of Elysium', "Clear Elysium with the 'Extreme Measures' Condition"),
      ach('steam-hades-32', 'steam', 'Musician and Muse', "Fulfill the 'Musician and Muse' Prophecy"),
      ach('steam-hades-33', 'steam', 'Haste of Hermes', 'Get 20% dodge chance with the Lambent Plume'),
      ach('steam-hades-34', 'steam', 'Bad Call', "Use an Olympian's Greater Call against them in a Trial"),
      ach('steam-hades-35', 'steam', 'The Useless Trinket', "Earn the first of Skelly's prizes"),
      ach('steam-hades-36', 'steam', 'Thanks, But No Thanks', 'Purge a Legendary Boon'),
      ach('steam-hades-37', 'steam', 'Slashed Benefits', "Fulfill the 'Slashed Benefits' Prophecy"),
      ach('steam-hades-38', 'steam', "Nyx's Mirror", 'Have at least one rank in each Mirror of Night Talent'),
      ach('steam-hades-39', 'steam', 'Night and Darkness', "Fulfill the 'Night and Darkness' Prophecy"),
      ach('steam-hades-40', 'steam', 'End to Torment', "Fulfill the 'End to Torment' Prophecy"),
    ],
  },
];

export const CATALOG_BY_ID = new Map(CATALOG_GAMES.map((g) => [g.id, g]));

export function cloneCatalogGameToLibrary(g: CatalogGame): Game {
  return {
    id: `${g.id}-${Date.now()}`,
    platform: g.platform,
    title: g.title,
    artwork: g.artwork,
    source: {
      kind: 'catalog',
      externalId: g.id,
      url: g.sourceUrl,
    },
    achievements: g.achievements.map((a) => ({ ...a, id: `${a.id}-${Date.now()}-${Math.random().toString(16).slice(2)}` })),
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };
}
